# backend/docker-compose.yaml
version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8085:8085"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
